#!/usr/bin/env bash
# pd3.sh <rel|lab> <conf|start [fresh] [order: e.g. "236 237 235"]|stop|check|cycle> — 3-node PD cluster on the lab VMs.
# rel = official apache-hugegraph-incubating-1.7.0 PD (JDK 11), lab = the master build in ~/hugegraph/hugegraph-pd (JDK 17).
# cycle = conf, fresh start, check, stop, restart with the old leader last (so the leader moves), check.
B=$1; CMD=$2; shift 2
NODES="235 236 237"; SSH="ssh -n -o ConnectTimeout=15 -o BatchMode=yes"
if [ "$B" = rel ]; then D='~/rel-1.7.0/apache-hugegraph-incubating-1.7.0/apache-hugegraph-pd-incubating-1.7.0'; JH='$HOME/tools/jdk11'; else D='~/hugegraph/hugegraph-pd/apache-hugegraph-pd-1.7.0'; JH='$HOME/tools/jdk17'; fi
PEERS="192.168.80.235:8610,192.168.80.236:8610,192.168.80.237:8610"; STORES="192.168.80.235:8500,192.168.80.236:8500,192.168.80.237:8500"
conf() { for N in $NODES; do $SSH seba@192.168.80.$N "cd $D/conf && [ -f application.yml.orig ] || cp application.yml application.yml.orig; sed -i -E 's/^(\s*host:\s*).*/\1192.168.80.$N/; s/^(\s*address:\s*).*/\1192.168.80.$N:8610/; s/^(\s*peers-list:\s*).*/\1$PEERS/; s/^(\s*initial-store-count:\s*).*/\13/; s/^(\s*initial-store-list:\s*).*/\1$STORES/' application.yml; grep -E '^\s*(host|address|peers-list|initial-store-count):' application.yml | tr '\n' ' '"; echo; done; }
stop() { for N in $NODES; do $SSH seba@192.168.80.$N "(cd $D && ./bin/stop-hugegraph-pd.sh) >/dev/null 2>&1; sleep 2; for p in 8686 8620 8610; do P=\$(ss -tlnp 2>/dev/null | grep \":\$p \" | grep -o 'pid=[0-9]*' | head -1 | cut -d= -f2); [ -n \"\$P\" ] && kill -9 \$P; done; sleep 1; echo \"  $N stopped (\$(ss -tln | grep -qE ':(8686|8620|8610) ' && echo PORTS BUSY || echo ok))\""; done; }
start1() { N=$1; FRESH=$2; $SSH seba@192.168.80.$N "cd $D && export JAVA_HOME=$JH PATH=$JH/bin:/usr/bin:/bin:/usr/sbin; [ '$FRESH' = fresh ] && rm -rf pd_data logs/*.log; rm -f bin/pid; ./bin/start-hugegraph-pd.sh >/dev/null 2>&1; for i in \$(seq 1 30); do ss -tln | grep -q ':8620 ' && break; sleep 2; done; echo \"  $N started \$(date +%T) (8620 \$(ss -tln | grep -q ':8620 ' && echo up || echo DOWN))\""; }
start() { FRESH=$1; ORDER=${2:-$NODES}; for N in $ORDER; do start1 $N $FRESH; done; sleep 15; }
check() { for N in $NODES; do $SSH seba@192.168.80.$N "cd $D; M=\$(curl -s -m 10 -u hg: http://127.0.0.1:8620/v1/members); L=\$(echo \"\$M\" | grep -o '\"pdLeader\":{[^}]*}' | grep -o '\"raftUrl\":\"[^\"]*\"' | head -1); C=\$(echo \"\$M\" | grep -o '\"stateCountMap\":{[^}]*}'); G=\$(echo \"\$M\" | grep -o '\"grpcUrl\":\"[^\"]*\"' | sort | uniq -c | tr '\n' ' '); ST=\$(curl -s -m 15 -o /dev/null -w '%{http_code}' -u hg: http://127.0.0.1:8620/v1/stores); SB=\$(curl -s -m 15 -u hg: http://127.0.0.1:8620/v1/stores | head -c 120 | tr -d '\n'); R=\$(cat logs/hugegraph-pd.log | grep -ic 'redirect to leader'); F=\$(grep -c 'failed to call rpc' logs/hugegraph-pd.log); LM=\$(grep -h -iE 'become leader|onLeaderStart|leader start' logs/hugegraph-pd_raft.log logs/hugegraph-pd.log 2>/dev/null | tail -1 | cut -c1-19); echo \"  $N: leader=\$L counts=\$C grpcUrls=[\$G] /v1/stores=\$ST \$SB | redirect-errors=\$R rpc-failures=\$F last-leader-marker=\$LM\""; done; }
case $CMD in
  conf) conf;; stop) stop;; start) start "$1" "$2";; check) check;;
  cycle) echo "== conf"; conf; echo "== stop everything"; stop; echo "== fresh start 235 236 237"; start fresh "235 236 237"; echo "== check #1"; check
         LEADER=$(for N in $NODES; do $SSH seba@192.168.80.$N "cd $D; grep -h -iE 'become leader|onLeaderStart|leader start' logs/hugegraph-pd_raft.log logs/hugegraph-pd.log 2>/dev/null | tail -1 | cut -c1-19 | sed 's/\$/ $N/'"; done | sort | tail -1 | awk '{print $NF}')
         echo "== leader was $LEADER; stop all, restart with $LEADER last"; stop; ORDER="$(echo $NODES | tr ' ' '\n' | grep -v "^$LEADER$" | tr '\n' ' ') $LEADER"; echo "order: $ORDER"; for N in $ORDER; do start1 $N keep; [ "$N" != "$LEADER" ] && sleep 5; done; sleep 20; echo "== check #2 (after restart)"; check; sleep 30; echo "== check #3 (+30 s)"; check;;
esac
